# Generated by Django 3.2.7 on 2021-09-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(default='Berita Roda Indonesia', max_length=100)),
                ('news_description', models.TextField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
