# Generated by Django 3.2.7 on 2021-09-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published',
            new_name='is_published',
        ),
    ]
